### PR TITLE
Minor changes README#Tests.

### PR DESCRIPTION
**Pull request by julien-f**

### CODE REVIEW

**Comment by LinusU** [comment]
Is there any upside to using anything else than the python thing? Python is available on OS X and nearly every Linux dist.

Maybe the best would be du include `http-server` as a `devDepenencie` and add a `scripts` entry for running it?

**Comment by julien-f** [comment]
Nope, there is no particular upside in using `http-server` but I don't know if the `SimpleHTTPServer` module is available everywhere.

Anyway, it makes sense to me to propose an Node alternative.

**Comment by LinusU** [comment]
`SimpleHTTPServer` is built in to the standard python library so that should always be available. I also like the idea of promoting a Node.js alternative, but I don't like listing more than one choice. That pushes the decision on to the end user which increases cognitive load. Also, the python route is a straight forward command which have no downside other than being python rather than node.js. http-server in this case is a link where you need to read up on how to use it.

What do you think about adding a `scripts` entry in the package.json?

**Comment by julien-f** [comment]
Yep, that seems to be the best way.

**Comment by LinusU** [comment]
Fantastic, I will try to test this tonight (Swedish time) and then merge!

**Comment by julien-f** [comment]
@LinusU I intend to make a release ASAP, any last comments on this PR?

**Comment by LinusU** [comment]
LGTM :+1:

**Pull request merged**
