### PR TITLE
Cache failed source map lookup attempts

### PR DESCRIPTION
**Pull request by khalsah**
I was getting terrible performance in a test suite when I added source-map-support and realized it was because it was repeatedly trying to retrieve the source map for a javascript file that has no source map.

This pull request adds logic to cache lookup failures in addition to lookup success which improved performance substantially.

### CODE REVIEW

**Comment by crispy1989** [comment]
Looks useful.  Any word on this?

**Comment by Flickdm** [comment]
+1

**Comment by julien-f** [comment]
@khalsah Is it still relevant?

**Comment by khalsah** [comment]
Looks like this problem was solved by af37071383bb87d529028ad6dfe665584c9313b8. Should no longer be needed.

**Pull request closed without merging**
