### PR TITLE
Allow for multiple install calls

### PR DESCRIPTION
**Pull request by kpdecker**
This allows for multiple libraries to utilize this without stepping on each other’s toes.

This makes the retrieve helpers additive, giving priority to the last retrieve method registered. In the event of a miss, the next method is called up to and including the default behavior. The `overrideRetriveFile` and `overrideRetrieveSourceMap` flags are added if this behavior is not desired but this is something that most libraries should avoid to be good citizens.

Flagged behaviors will now be on if any of the install calls dictate that they would be.

Fix for #91

### CODE REVIEW

**Comment by kpdecker** [comment]
Looks like the build failure is due to an iojs string matching issue vs. these changes in particular.

**Comment by kpdecker** [comment]
Any chance on feedback here? I also have a patch that adds support map support for runtime transpiled files that have inline source maps attached but it depends on many of the things here.

**Comment by LinusU** [comment]
@kpdecker Sorry for the silence, would you mind rebasing on master?

**Comment by kpdecker** [comment]
Rebased

**Comment by LinusU** [comment]
I think this looks good :+1:

I'll give the other maintainers a few days to look at this, if there are no problems we'll merge it.

@julien-f Feel free to merge if you think it looks good :+1:

**Comment by kpdecker** [comment]
Any thoughts on this?

**Comment by LinusU** [comment]
Merging :+1:

**Comment by LinusU** [comment]
Released as `0.4.0`

**Pull request merged**
