### PR TITLE
Add note about -r when using with node

### LINKED ISSUE #113: use -r when using in node
Another method (as of [io.js 2.2.0](https://github.com/nodejs/node/blob/master/CHANGELOG.md#2015-05-31-version-220-rvagg)) is to use the `-r` flag in node, e.g., `node -r source-map-support/register foo.js` which will remove the need to modify compiled code.

### PR DESCRIPTION
**Pull request by apechimp**
This resolves #113

### CODE REVIEW

**Comment by LinusU** [comment]
This looks very good, mind rebasing on top of master?

**Comment by apechimp** [comment]
@LinusU I've rebased.

**Comment by uiteoi** [comment]
Option ```-r``` was added in Node ```v1.6.0```

https://nodejs.org/api/cli.html#cli_r_require_module

**Comment by LinusU** [comment]
I think that everyone is using Node.js 4 or newer, can we skip mentioning versions of Node at all and just give them titles like "CLI Usage" and "Programmatic Usage"?

**Comment by uiteoi** [comment]
Skipping mentioning the version is fine, but if we mention a version might as well be the correct one.

**Comment by apechimp** [comment]
_Technically_, the version is correct 😛  Although, this feature has been around since `1.8.0`, it didn't work with things in `node_modules` until `2.2.0`. See the second bullet point [here](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_IOJS.md#2.2.0). That being said. Two years later, no one cares about versions 1-3, so I'll adjust the note.

**Comment by LinusU** [comment]
Thanks!

**Comment by LinusU** [comment]
Published in 0.5.1

**Pull request merged**
