### PR TITLE
Fixed sourcemap url detection from code.

### LINKED ISSUE #57: Misleading sourceMappingURL detection within source
I append in transpiler the sourceMappingURL through the code...

```javascript
code + '//# sourceMappingURL=' + sourcemap_path;
```

The sourceMappingURL match regexp detects it as url and tries to fetch "' + sourcemap_path;"... and for minified code is even worse...

### PR DESCRIPTION
**Pull request by marcominetti**
Brutally fixes #57 ... Assuming there is never ' or " within the uri...

### CODE REVIEW

**Comment by marcominetti** [comment]
@julien-f quick review before merge?

**Comment by julien-f** [comment]
I do not think the URL may be surrounded by quotes nor prefixed by spaces.

Appart from that I think it's fair to assume that an URL should not contain any quote because the source map spec say:
> `<url>` is a URL as defined in RFC3986; in particular, characters outside the set permitted to appear in URIs must be percent-encoded.

**Comment by marcominetti** [comment]
I agree...

**Comment by marcominetti** [comment]
I've included the surrounded quotes match, just in case the specs or any custom implementation change...

**Comment by julien-f** [comment]
I think, for now, it should be enough to just change `(.*)` to `([^'"]+)`.

Would that be enough to fix your problem?

**Comment by marcominetti** [comment]
Yep, I change the code and squash commits...

**Pull request merged**
