### PR TITLE
add info about node 12.12.0 `--enable-source-maps`

### LINKED ISSUE #321: document that this package is no longer needed as of node 12.12.0
the `--enable-source-maps` flag was added in nodejs 12.12.0, meaning this package is no longer required for node
https://nodejs.org/en/blog/release/v12.12.0/

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #321

### CODE REVIEW

**Comment by KotlinIsland** [comment]
LGTM!

**Comment by sheremet-va** [comment]
I just want to point out that `--enable-source-maps` doesn't work with `vm.runInThisContext`. So tools like Jest and Vite still need to use the package.

**Comment by DetachHead** [comment]
@LinusU where is that quote from? in my experience source maps have worked in both jest and vite without needing to use this package

**Comment by sheremet-va** [comment]
This is because jest already includes it. I meant that this package is required for lib developers, not necessarily users.

**Comment by DetachHead** [comment]
i feel like this information is a bit too low level for most users. i think the vast majority of people who stumble upon this package aren't developers of jest or vite, and wouldn't have a clue what `vm` and `vm.runInThisContext` is.

i will include it if you guys think it's necessary, however i think installation instructions should be as simple as possible

**Comment by DetachHead** [comment]
how's that?

**Review by LinusU — APPROVED** [review]
That's great, thanks! 🙏

**Comment by LinusU** [comment]
> i feel like this information is a bit too low level for most users. i think the vast majority of people who stumble upon this package aren't developers of jest or vite, and wouldn't have a clue what `vm` and `vm.runInThisContext` is.
> 
> i will include it if you guys think it's necessary, however i think installation instructions should be as simple as possible

Sorry, merged before I read this. Yeah, might have been unnecessary but I think with the parenthesis it turned out nice 👍

**Pull request merged**
