### PR TITLE
add es6 string delimiter for sourceMappingURL matching

### PR DESCRIPTION
**Pull request by LongTengDao**

### CODE REVIEW

**Comment by LinusU** [comment]
Would you mind adding a test for this (in `test.js`, it's using [mocha](https://mochajs.org))? Thanks!

**Comment by LongTengDao** [comment]
> Would you mind adding a test for this (in `test.js`, it's using [mocha](https://mochajs.org))? Thanks!

Thanks for notice! I found more problem just now, when I try to add a test.

In my PR, I just add an obvious fix; But when I read the context, I found the function `retrieveSourceMapURL` will never return the url of `/*# sourceMappingURL=filename */` which the `re` tried to match.

I'm not sure what does this area of codes want to do, `sourceMappingURL` in `/* */` is valid, or invalid?

**Comment by LinusU** [comment]
Just pasting this quickly in my browser seems to work 🤔

screenshot 2019-01-12 at 19 36 18

Would you mind providing some more details? ☺️

**Comment by LongTengDao** [comment]
> Just pasting this quickly in my browser seems to work 🤔
> 
> screenshot 2019-01-12 at 19 36 18
> 
> Would you mind providing some more details? ☺️

Final returning is `lastMatch[1]`, which is will be `undefined` in your screenshot. If you are sure this is another bug, not a feature for unknown purpose, fixing it is easy.

**Comment by LongTengDao** [comment]
> Hehe, I'm guessing that we have a bug currently that only accepts `//# sourceMappingURL=filename` and not `/*# sourceMappingURL=filename */`...
> 
> I think that the correct fix would be to change to `return result[1] || result[2]`

Let me try to give it a whole fix. Because even if we do `[1] || [2]`, there are still other problems, like:

```js
'/*# sourceMappingURL=';//# sourceMappingURL=map*/
```

or:

```js
/*
//# sourceMappingURL=I/am/not/a/sourceMappingURL/and/you/should/match/nothing.
*/
```

**Comment by LongTengDao** [comment]
I close this PR, and create a new one, which just fix the `/* */` matching bug.

**Pull request closed without merging**
